// The Cloudflare entry point.
//
// Cloudflare answers requests from many isolates, so a demo store held in isolate memory is
// gone by the next click. Each browser session is therefore pinned to its own Durable Object,
// which is a single instance for a given id: every request from that viewer runs in the same
// place. The object also writes the session's stores to its own storage after each change, so
// a viewer who steps away and comes back finds the demo as they left it rather than reseeded.
//
// Excluded from tsconfig because .open-next/worker.js only exists after a build.
import { DurableObject } from "cloudflare:workers";
import { SESSION_COOKIE, runWithSession } from "./lib/session";
import { restoreSession, snapshotSession } from "./lib/store-sessions";
// @ts-expect-error generated by `opennextjs-cloudflare build`
import nextHandler from "./.open-next/worker.js";

type Handler = { fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> };
type Env = { DEMO_PASSPHRASE?: string; DEMO_SESSION: DurableObjectNamespace };

const SESSION_HEADER = "x-demo-session";
// Durable Object storage holds at most 128 KiB per value, so the snapshot is split.
const CHUNK = 90_000;
const COUNT_KEY = "chunks";

/** Holds one viewer's demo state, in memory while they are clicking and in storage between. */
export class DemoSession extends DurableObject {
  private loaded = false;
  private lastSaved: string | null = null;

  private async load(id: string): Promise<void> {
    if (this.loaded) return;
    this.loaded = true;
    try {
      const count = await this.ctx.storage.get<number>(COUNT_KEY);
      if (!count) return;
      const keys = Array.from({ length: count }, (_, i) => `c${i}`);
      const parts = await this.ctx.storage.get<string>(keys);
      let text = "";
      for (let i = 0; i < count; i++) text += parts.get(`c${i}`) ?? "";
      if (!text) return;
      restoreSession(id, JSON.parse(text) as Record<string, unknown>);
      this.lastSaved = text;
    } catch {
      // A snapshot we cannot read is not worth failing a demo over: start from the seed.
    }
  }

  private async save(id: string): Promise<void> {
    try {
      const snapshot = snapshotSession(id);
      if (!snapshot) return;
      const text = JSON.stringify(snapshot);
      if (text === this.lastSaved) return;
      const chunks: Record<string, string | number> = {};
      let n = 0;
      for (let i = 0; i < text.length; i += CHUNK) chunks[`c${n++}`] = text.slice(i, i + CHUNK);
      chunks[COUNT_KEY] = n;
      await this.ctx.storage.deleteAll();
      await this.ctx.storage.put(chunks);
      this.lastSaved = text;
    } catch {
      // Storage is a convenience here; the store is still live in memory for this session.
    }
  }

  async fetch(request: Request): Promise<Response> {
    const id = request.headers.get(SESSION_HEADER) ?? "shared";
    await this.load(id);
    const ctx = {
      waitUntil: (promise: Promise<unknown>) => {
        try {
          (this.ctx as unknown as { waitUntil(p: Promise<unknown>): void }).waitUntil(promise);
        } catch {
          void promise;
        }
      },
      passThroughOnException: () => {},
    };
    const response = await runWithSession(id, () => (nextHandler as Handler).fetch(request, this.env, ctx));
    // Most reads cannot change the demo, but a few do: the Yardi export is a GET that marks the
    // batch exported. Save after any request that reached a route handler; save() is a no-op when
    // nothing actually changed, so a plain page view costs nothing.
    const isApi = new URL(request.url).pathname.startsWith("/api/");
    if (isApi || (request.method !== "GET" && request.method !== "HEAD")) await this.save(id);
    return response;
  }
}

function sessionFrom(request: Request): string | null {
  const raw = request.headers.get("cookie");
  if (!raw) return null;
  for (const part of raw.split(";")) {
    const [name, ...value] = part.trim().split("=");
    if (name === SESSION_COOKIE && value.length > 0) return value.join("=");
  }
  return null;
}

/** Same-length comparison so a wrong passphrase cannot be guessed a character at a time. */
function matches(given: string, expected: string): boolean {
  if (given.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < given.length; i++) diff |= given.charCodeAt(i) ^ expected.charCodeAt(i);
  return diff === 0;
}

/**
 * Off unless a DEMO_PASSPHRASE secret is set on the Worker, which is how the link is locked
 * to the people who have been given the passphrase:
 *   npx wrangler secret put DEMO_PASSPHRASE
 */
function locked(request: Request, expected: string): boolean {
  const header = request.headers.get("authorization") ?? "";
  if (!header.toLowerCase().startsWith("basic ")) return true;
  try {
    const decoded = atob(header.slice(6).trim());
    const given = decoded.slice(decoded.indexOf(":") + 1);
    return !matches(given, expected);
  } catch {
    return true;
  }
}

const worker = {
  async fetch(request: Request, env: Env, ctx: unknown): Promise<Response> {
    if (env.DEMO_PASSPHRASE && locked(request, env.DEMO_PASSPHRASE)) {
      return new Response("This demo is private. Ask the presenter for the passphrase.", {
        status: 401,
        headers: { "www-authenticate": 'Basic realm="AP demo suite", charset="UTF-8"' },
      });
    }

    const known = sessionFrom(request);
    const id = known ?? crypto.randomUUID();

    let response: Response;
    if (env.DEMO_SESSION) {
      const forwarded = new Request(request);
      forwarded.headers.set(SESSION_HEADER, id);
      const stub = env.DEMO_SESSION.get(env.DEMO_SESSION.idFromName(id));
      response = await stub.fetch(forwarded);
    } else {
      // No Durable Object bound (local `next dev` style runs): one shared store, as before.
      response = await runWithSession(id, () => (nextHandler as Handler).fetch(request, env, ctx));
    }

    if (known) return response;
    const withCookie = new Response(response.body, response);
    withCookie.headers.append("set-cookie", `${SESSION_COOKIE}=${id}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=86400`);
    return withCookie;
  },
};

export default worker;
