import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { createStore, loadSeed } from "../store";
import { runMonth, undoLast, type Canned } from "../lib/run";
import { queue, resolveException, blockedDuplicates } from "../lib/exceptions";
import { markExported, buildUpload } from "../lib/export";
import { yardiImport } from "../lib/import";
import { ambiguousQueue, confirmMatch } from "../lib/matches";
import { providerImport, applySiteVisit, stepMonth, monthStepper } from "../lib/mechanisms";
import { actionList, doBillBack, doTransfer } from "../lib/actions";
import { cellFor, indexStore, monthCounts, rowFlags, missingBillSweep } from "../lib/status";

const canned = JSON.parse(fs.readFileSync(path.join(process.cwd(), "data", "canned-extractions.json"), "utf8")) as Canned;
const AUG = "2026-08";
const SEP = "2026-09";

describe("the August run", () => {
  const store = createStore(loadSeed());
  const S = store.scripted;
  const meter = (id: string) => store.meters.find((m) => m.id === id)!;
  const bill = (id: string) => store.bills.find((b) => b.id === id)!;

  it("starts with the scripted statuses", () => {
    const ix = indexStore(store);
    expect(cellFor(ix, meter(S["A-1"]), AUG).status).toBe("unpaid");
    expect(cellFor(ix, meter(S["A-6"]), AUG).status).toBe("no_account");
    expect(cellFor(ix, meter(S["A-2"]), AUG).status).toBe("transfer_needed");
    expect(cellFor(ix, meter(S["A-2"]), "2026-07")).toMatchObject({ status: "bill_back", months_since_move_in: 4 });
    expect(cellFor(ix, meter(S["B-3"]), AUG).status).toBe("not_yet_billed");
    expect(rowFlags(ix, meter(S["A-8"]), AUG).payer_carried_over).toBe(true);
    expect(rowFlags(ix, meter(S["A-2"]), AUG).transfer_needed).toBe(true);
    const mc = monthCounts(ix, AUG);
    expect(mc.no_account).toBeGreaterThanOrEqual(200);
    expect(mc.blank_meters).toBeGreaterThanOrEqual(190);
  });
  it("ticks every step and queues the scripted exceptions", () => {
    const r = runMonth(store, AUG, canned);
    expect(r.received.emailed + r.received.downloaded).toBeGreaterThan(200);
    expect(r.fields_read).toBe(r.received.emailed + r.received.downloaded);
    expect(r.matched).toBeGreaterThan(100);
    expect(r.surfaced).toBeGreaterThanOrEqual(60);
    expect(r.unmapped).toBeGreaterThanOrEqual(10);
    expect(r.meter_differs).toBeGreaterThanOrEqual(1);
    expect(r.duplicates).toBe(1);
    expect(r.unusual).toBeGreaterThanOrEqual(1);
    expect(bill(S["B-6"]).status).toBe("blocked");
    expect(bill(S["B-6"]).duplicate_of).toBe(S["B-6-first"]);
    const q = queue(store, AUG);
    expect(q.find((e) => e.bill_id === S["A-5"])?.type).toBe("meter_differs");
    expect(q.find((e) => e.bill_id === S["B-7"])?.type).toBe("unusual_amount");
    expect(q.find((e) => e.bill_id === S["B-4"])?.type).toBe("unmapped");
    expect(q.find((e) => e.bill_id === S["B-4"])?.suggestion?.meter_id).toBe(S["B-4-meter"]);
    expect(blockedDuplicates(store, AUG)).toHaveLength(1);
    const ix = indexStore(store);
    expect(monthCounts(ix, AUG).no_account).toBeLessThan(200);
  });
  it("resolves B-4 with the suggestion and undo restores it", () => {
    const ex = queue(store, AUG).find((e) => e.bill_id === S["B-4"])!;
    resolveException(store, ex.id, { kind: "accept" });
    expect(bill(S["B-4"]).meter_id).toBe(S["B-4-meter"]);
    expect(store.accounts.some((a) => a.account_number === bill(S["B-4"]).account_number && a.meter_id === S["B-4-meter"])).toBe(true);
    expect(undoLast(store)).toContain("unmapped");
    expect(bill(S["B-4"]).status).toBe("unmapped");
    expect(store.exceptions.find((e) => e.id === ex.id)?.status).toBe("open");
    resolveException(store, ex.id, { kind: "accept" });
    expect(bill(S["B-4"]).status).toBe("matched");
  });
  it("confirms the A-5 swap, drops the B-6 duplicate, acknowledges B-7 with a verify action", () => {
    const a5 = queue(store, AUG).find((e) => e.bill_id === S["A-5"])!;
    const m = meter(a5.meter_id!);
    const before = m.meter_number;
    resolveException(store, a5.id, { kind: "swap" });
    expect(m.meter_number).toBe(bill(S["A-5"]).meter_as_printed);
    expect(m.notes.some((n) => n.includes(before ?? "blank"))).toBe(true);
    const b6 = queue(store, AUG).find((e) => e.bill_id === S["B-6"])!;
    expect(buildUpload(store, AUG).rows.some((r) => r.bill_id === S["B-6"])).toBe(false);
    resolveException(store, b6.id, { kind: "drop_second" });
    expect(blockedDuplicates(store, AUG)).toHaveLength(0);
    const b7 = queue(store, AUG).find((e) => e.bill_id === S["B-7"])!;
    expect(Number(b7.details.ratio)).toBeGreaterThan(2.5);
    resolveException(store, b7.id, { kind: "acknowledge", reason: "vacant but in use" });
    expect(store.verify_items.some((v) => v.property_id === "P02" && v.reason.includes("vacant but in use"))).toBe(true);
  });
  it("exports, imports, and flips the batch to Paid including the three-line water bill", () => {
    const ix0 = indexStore(store);
    expect(cellFor(ix0, meter("M9100087"), AUG).status).toBe("unpaid");
    const exported = markExported(store, AUG);
    expect(exported.files.some((f) => f.name.startsWith("0999001-"))).toBe(true);
    expect(bill(S["B-6"]).status).toBe("blocked");
    const imported = yardiImport(store, AUG);
    expect(imported.lines).toBe(exported.rows);
    const ix = indexStore(store);
    const b5 = cellFor(ix, meter("M9100087"), AUG);
    expect(b5.status).toBe("paid");
    expect(b5.line_ids).toHaveLength(3);
    expect(cellFor(ix, meter(S["A-1"]), AUG).status).toBe("unpaid");
    expect(cellFor(ix, meter(S["A-6"]), AUG).status).toBe("no_account");
    expect(cellFor(ix, meter(S["B-3"]), AUG).status).toBe("not_yet_billed");
    const mc = monthCounts(ix, AUG);
    expect(mc.unpaid).toBeGreaterThanOrEqual(3);
    expect(mc.unpaid).toBeLessThanOrEqual(8);
    expect(mc.exact_lines / mc.matched_lines).toBeGreaterThan(0.95);
  });
  it("lists A-7 for confirmation with two candidates and assigns it", () => {
    const amb = ambiguousQueue(store, AUG);
    const a7 = amb.find((x) => x.match.line.id === S["A-7"])!;
    expect(a7.candidates).toHaveLength(2);
    confirmMatch(store, S["A-7"], a7.candidates[0].account.account_number);
    expect(ambiguousQueue(store, AUG).some((x) => x.match.line.id === S["A-7"])).toBe(false);
  });
  it("sweeps B-3's provider accounts onto the call list with last bill dates", () => {
    const ix = indexStore(store);
    const sweep = missingBillSweep(ix, AUG);
    expect(sweep.some((s) => s.meter.id === S["A-1"])).toBe(true);
    const b3 = sweep.find((s) => s.meter.id === S["B-3"])!;
    expect(b3.provider).toBe("City of Rivermouth");
    expect(b3.last_bill_date).toMatch(/^2026-07/);
    const list = actionList(store, "P02", AUG);
    expect(list.call.some((g) => g.provider === "City of Rivermouth" && g.items.some((i) => i.meter.id === S["B-3"]))).toBe(true);
  });
  it("writes the A-2 bill-back row and a transfer draft", () => {
    const row = doBillBack(store, S["A-2"], AUG);
    expect(row.months).toBe(5);
    expect(row.amount).toBeGreaterThan(0);
    expect(row.gl_name).toBe("Tenant charges");
    const draft = doTransfer(store, S["A-2"], AUG);
    expect(draft.kind).toBe("tenant_letter");
    expect(draft.text).toContain(row.account_number);
    expect(draft.transfer_by > AUG).toBe(true);
    const a6 = doTransfer(store, S["A-6"], AUG);
    expect(a6.kind).toBe("provider_request");
  });
  it("runs the mechanisms and steps to September with the deltas", () => {
    const before = monthCounts(indexStore(store), AUG);
    const imp = providerImport(store, AUG);
    expect(imp.mapped).toBeGreaterThanOrEqual(25);
    expect(imp.ambiguous).toBeGreaterThanOrEqual(1);
    const mid = monthCounts(indexStore(store), AUG);
    expect(mid.no_account).toBeLessThan(before.no_account);
    const visit = applySiteVisit(store, AUG);
    expect(visit.filled).toBeGreaterThanOrEqual(40);
    expect(visit.verified).toBeGreaterThanOrEqual(30);
    const after = monthCounts(indexStore(store), AUG);
    expect(after.blank_meters).toBeLessThanOrEqual(50);
    expect(rowFlags(indexStore(store), meter(S["A-8"]), AUG).payer_carried_over).toBe(false);
    expect(cellFor(indexStore(store), meter(S["A-8"]), AUG).status).toBe("tenant_held");
    expect(after.no_account).toBeLessThanOrEqual(100);
    expect(stepMonth(store)).toBe(SEP);
    const stepper = monthStepper(store);
    expect(stepper.map((s) => s.month)).toEqual(["2026-07", AUG, SEP]);
    expect(stepper[1].counts?.no_account).toBe(after.no_account);
    expect(stepper[2].contributions.some((c) => c.mechanism === "provider_import")).toBe(true);
    const r2 = runMonth(store, SEP, canned);
    expect(r2.unmapped).toBeLessThan(5);
    expect(r2.surfaced).toBeLessThan(10);
    markExported(store, SEP);
    yardiImport(store, SEP);
    expect(ambiguousQueue(store, SEP).filter((x) => x.match.line.post_month === SEP)).toHaveLength(0);
    const sepCounts = monthCounts(indexStore(store), SEP);
    expect(sepCounts.no_account).toBeLessThan(before.no_account);
  });
});
